""" Add rama_id to productos and ensayos_es_x_productos table

Revision ID: 243c89ef446f
Revises: 441bfc1d0d93
Create Date: 2026-03-05 23:40:03.021740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243c89ef446f'
down_revision = '441bfc1d0d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensayos_es_x_productos',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ensayo_es_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ensayo_es_id'], ['ensayos_es.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'ensayo_es_id')
    )
    with op.batch_alter_table('ensayos_es_x_productos', schema=None) as batch_op:
        batch_op.create_index('ix_ensayos_es_x_productos_ensayo_es_id', ['ensayo_es_id'], unique=False)
        batch_op.create_index('ix_ensayos_es_x_productos_producto_id', ['producto_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('status_change_email', sa.Boolean(), nullable=False),
    sa.Column('delivery_email', sa.Boolean(), nullable=False),
    sa.Column('pending_alert_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rama_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_productos_rama_id', 'ramas', ['rama_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_productos_rama_id', type_='foreignkey')
        batch_op.drop_column('rama_id')

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('ensayos_es_x_productos', schema=None) as batch_op:
        batch_op.drop_index('ix_ensayos_es_x_productos_producto_id')
        batch_op.drop_index('ix_ensayos_es_x_productos_ensayo_es_id')

    op.drop_table('ensayos_es_x_productos')
    # ### end Alembic commands ###
