"""Initial migration - complete schema with all tables

Revision ID: 441bfc1d0d93
Revises: 
Create Date: 2026-03-04 06:37:21.454855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441bfc1d0d93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annos',
    sa.Column('anno', sa.String(length=4), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('anno')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_areas_sigla'), ['sigla'], unique=True)

    op.create_table('destinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destinos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destinos_sigla'), ['sigla'], unique=True)

    op.create_table('meses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('sigla', sa.String(length=5), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organismos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organismos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organismos_nombre'), ['nombre'], unique=True)

    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provincias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provincias_sigla'), ['sigla'], unique=True)

    op.create_table('ramas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ramas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ramas_nombre'), ['nombre'], unique=True)

    op.create_table('tipos_es',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tipos_es', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_es_nombre'), ['nombre'], unique=True)

    op.create_table('unidades_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unidades_medida', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unidades_medida_codigo'), ['codigo'], unique=True)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('organismo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_cliente', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organismo_id'], ['organismos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_codigo'), ['codigo'], unique=True)

    op.create_table('ensayos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_oficial', sa.String(length=500), nullable=False),
    sa.Column('nombre_corto', sa.String(length=200), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unidad_medida', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_ensayo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ensayos_es',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_oficial', sa.String(length=500), nullable=False),
    sa.Column('nombre_corto', sa.String(length=200), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('tipo_es_id', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unidad_medida', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['tipo_es_id'], ['tipos_es.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destino_id'], ['destinos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ensayos_x_productos',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ensayo_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ensayo_id'], ['ensayos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'ensayo_id')
    )
    op.create_table('fabricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'nombre', name='uix_fabrica_cliente_nombre')
    )
    op.create_table('ordenes_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nro_ofic', sa.String(length=30), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', name='ot_status'), nullable=False),
    sa.Column('fech_creacion', sa.DateTime(), nullable=False),
    sa.Column('fech_completado', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nro_ofic')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'LABORATORY_MANAGER', 'TECHNICIAN', 'CLIENT', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('orden_trabajo_id', sa.Integer(), nullable=True),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('lote', sa.String(length=20), nullable=True),
    sa.Column('fech_fab', sa.Date(), nullable=True),
    sa.Column('fech_venc', sa.Date(), nullable=True),
    sa.Column('fech_pedido', sa.DateTime(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', name='pedido_status'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['orden_trabajo_id'], ['ordenes_trabajo.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidades_medida.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('fabrica_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('rama_id', sa.Integer(), nullable=True),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('lote', sa.String(length=10), nullable=True),
    sa.Column('nro_parte', sa.String(length=50), nullable=True),
    sa.Column('cantidad_recib', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_entreg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_muest', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fech_fab', sa.Date(), nullable=True),
    sa.Column('fech_venc', sa.Date(), nullable=True),
    sa.Column('fech_muestreo', sa.Date(), nullable=True),
    sa.Column('fech_entrada', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('RECIBIDO', 'EN_PROCESO', 'COMPLETADO', 'ENTREGADO', 'ANULADO', name='entrada_status'), nullable=False),
    sa.Column('en_os', sa.Boolean(), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=True),
    sa.Column('ent_entregada', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['fabrica_id'], ['fabricas.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['rama_id'], ['ramas.id'], ),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidades_medida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entradas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entradas_codigo'), ['codigo'], unique=True)

    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=False),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entrada_id'], ['entradas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history')
    with op.batch_alter_table('entradas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entradas_codigo'))

    op.drop_table('entradas')
    op.drop_table('pedidos')
    op.drop_table('notifications')
    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('ordenes_trabajo')
    op.drop_table('fabricas')
    op.drop_table('ensayos_x_productos')
    op.drop_table('productos')
    op.drop_table('ensayos_es')
    op.drop_table('ensayos')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_codigo'))

    op.drop_table('clientes')
    with op.batch_alter_table('unidades_medida', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidades_medida_codigo'))

    op.drop_table('unidades_medida')
    with op.batch_alter_table('tipos_es', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_es_nombre'))

    op.drop_table('tipos_es')
    with op.batch_alter_table('ramas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ramas_nombre'))

    op.drop_table('ramas')
    with op.batch_alter_table('provincias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provincias_sigla'))

    op.drop_table('provincias')
    with op.batch_alter_table('organismos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organismos_nombre'))

    op.drop_table('organismos')
    op.drop_table('meses')
    with op.batch_alter_table('destinos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destinos_sigla'))

    op.drop_table('destinos')
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_sigla'))

    op.drop_table('areas')
    op.drop_table('annos')
    # ### end Alembic commands ###
