"""Update schema to latest models

Revision ID: 578f42f280ed
Revises: dd1714988574
Create Date: 2026-03-06 22:51:36.553023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578f42f280ed'
down_revision = 'dd1714988574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_ensayo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_numerico', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('valor_texto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('valor_booleano', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parametros_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resultado_cumple', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ensayos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especificacion_min', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('especificacion_max', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('especificacion_unidad', sa.String(length=20), nullable=True))

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fecha_emision',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('actualizado_en',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_facturas_estado'))

    with op.batch_alter_table('utilizados', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('precio_unitario',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('importe',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('fecha_uso',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('actualizado_en',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_utilizados_detalle_ensayo_id'), ['detalle_ensayo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utilizados_ensayo_id'), ['ensayo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utilizados_entrada_id'), ['entrada_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utilizados_factura_id'), ['factura_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilizados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilizados_factura_id'))
        batch_op.drop_index(batch_op.f('ix_utilizados_entrada_id'))
        batch_op.drop_index(batch_op.f('ix_utilizados_ensayo_id'))
        batch_op.drop_index(batch_op.f('ix_utilizados_detalle_ensayo_id'))
        batch_op.alter_column('actualizado_en',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('fecha_uso',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('importe',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('precio_unitario',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_estado'), ['estado'], unique=False)
        batch_op.alter_column('actualizado_en',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('fecha_emision',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ensayos', schema=None) as batch_op:
        batch_op.drop_column('especificacion_unidad')
        batch_op.drop_column('especificacion_max')
        batch_op.drop_column('especificacion_min')

    with op.batch_alter_table('detalles_ensayo', schema=None) as batch_op:
        batch_op.drop_column('resultado_cumple')
        batch_op.drop_column('parametros_json')
        batch_op.drop_column('valor_booleano')
        batch_op.drop_column('valor_texto')
        batch_op.drop_column('valor_numerico')

    # ### end Alembic commands ###
