"""Add DetalleEnsayo model with state machine for test assignment

Revision ID: abeec908fc2d
Revises: 243c89ef446f
Create Date: 2026-03-06 00:21:47.086793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abeec908fc2d'
down_revision = '243c89ef446f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalles_ensayo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('ensayo_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_asignado_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ASIGNADO', 'EN_PROCESO', 'COMPLETADO', 'REPORTADO', name='detalle_ensayo_status'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ensayo_id'], ['ensayos.id'], ),
    sa.ForeignKeyConstraint(['entrada_id'], ['entradas.id'], ),
    sa.ForeignKeyConstraint(['tecnico_asignado_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entrada_id', 'ensayo_id', name='uq_detalle_entrada_ensayo')
    )
    with op.batch_alter_table('detalles_ensayo', schema=None) as batch_op:
        batch_op.create_index('ix_detalle_entrada_estado', ['entrada_id', 'estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalles_ensayo_entrada_id'), ['entrada_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_ensayo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalles_ensayo_entrada_id'))
        batch_op.drop_index('ix_detalle_entrada_estado')

    op.drop_table('detalles_ensayo')
    # ### end Alembic commands ###
